// LandMatch — mock data for Phase 5 dashboard prototype
// Based on schema in packages/db/src/schema.ts and scoring/types.ts

const PROFILES = [
  {
    id: 'p1',
    name: 'Hudson Valley homestead',
    alertFrequency: 'daily',
    alertThreshold: 70,
    isActive: true,
    counts: { new: 4, total: 37 },
    sub: 'Daily · ≥70 · 60mi of Kingston NY',
  },
  {
    id: 'p2',
    name: 'Ozark small farm',
    alertFrequency: 'weekly',
    alertThreshold: 65,
    isActive: true,
    counts: { new: 2, total: 18 },
    sub: 'Weekly · ≥65 · NW Arkansas',
  },
  {
    id: 'p3',
    name: 'Catskills weekender',
    alertFrequency: 'instant',
    alertThreshold: 75,
    isActive: false,
    counts: { new: 0, total: 6 },
    sub: 'Paused · instant · ≥75',
  },
];

// Each match references a listing + score. Matches are what lands in the inbox.
const MATCHES = [
  {
    id: 'm1',
    profileId: 'p1',
    unread: true,
    shortlisted: false,
    dismissed: false,
    time: '2h',
    source: 'LandWatch',
    foundAt: 'Apr 18 · 09:42',
    title: '12.4 acres · Stone Ridge, Ulster County NY',
    address: '483 High Falls Rd, Stone Ridge, NY 12484',
    lat: 41.861,
    lng: -74.144,
    price: 389000,
    acreage: 12.4,
    ppa: 31371,
    scoreOverall: 86,
    tier: 'STRONG MATCH',
    summary:
      'Class II loam on south-facing slope with partial pasture, minimal flood risk (Zone X), and agricultural zoning. Existing well and driveway; check septic permit and Starlink line-of-sight before visiting.',
    scores: { soil: 88, flood: 100, price: 74, acreage: 92, zoning: 95, geography: 90, infrastructure: 70, climate: 80 },
    tags: [
      { label: 'Class II soil', tone: 'green' },
      { label: 'Zone X flood', tone: 'green' },
      { label: 'Agricultural', tone: 'gold' },
      { label: 'Has well', tone: 'clay' },
    ],
    soil: {
      class: 2,
      classLabel: 'Good — moderate limitations',
      drainage: 'Well drained',
      texture: 'Silt loam',
      primeFarmland: 'Yes (with drainage)',
    },
    flood: {
      zone: 'X',
      zoneLabel: 'Minimal risk',
      femaPanel: '36111C0325D',
      effective: '2014-07-02',
    },
    parcel: {
      zoning: 'RA — Rural Agricultural',
      verifiedAcreage: '12.38',
      apn: '38.02-1-24',
    },
    climate: {
      fire: 2,
      flood: 1,
      heat: 3,
      drought: 2,
    },
    infra: ['Well', 'Electric on-site', 'County road', 'No septic on record'],
    sourcesUsed: ['USDA SDM', 'FEMA NFHL', 'Regrid', 'First Street'],
    sourcesSkipped: [],
  },
  {
    id: 'm2',
    profileId: 'p1',
    unread: true,
    shortlisted: true,
    dismissed: false,
    time: '5h',
    source: 'LandWatch',
    foundAt: 'Apr 18 · 06:11',
    title: '28 acres · Rosendale, Ulster County NY',
    address: 'Lower Granite Rd, Rosendale, NY 12472',
    lat: 41.842,
    lng: -74.079,
    price: 445000,
    acreage: 28,
    ppa: 15892,
    scoreOverall: 91,
    tier: 'TOP MATCH',
    summary:
      'Ideal size and price, Class I prime farmland with spring-fed pond, agricultural zoning, and southern exposure. One of the best listings this profile has seen — worth a site visit this week.',
    scores: { soil: 98, flood: 95, price: 88, acreage: 100, zoning: 95, geography: 88, infrastructure: 60, climate: 82 },
    tags: [
      { label: 'Prime farmland', tone: 'green' },
      { label: 'Spring-fed pond', tone: 'green' },
      { label: 'Under budget', tone: 'gold' },
    ],
    soil: { class: 1, classLabel: 'Prime farmland', drainage: 'Moderately well', texture: 'Silt loam', primeFarmland: 'Yes' },
    flood: { zone: 'X', zoneLabel: 'Minimal risk', femaPanel: '36111C0350D', effective: '2014-07-02' },
    parcel: { zoning: 'A — Agricultural', verifiedAcreage: '27.94', apn: '47.03-2-11' },
    climate: { fire: 2, flood: 2, heat: 3, drought: 2 },
    infra: ['Road frontage', 'Electric within 200ft', 'Pond'],
    sourcesUsed: ['USDA SDM', 'FEMA NFHL', 'Regrid', 'First Street'],
    sourcesSkipped: [],
  },
  {
    id: 'm3',
    profileId: 'p1',
    unread: false,
    shortlisted: false,
    dismissed: false,
    time: '1d',
    source: 'Land.com',
    foundAt: 'Apr 17 · 14:28',
    title: '6.2 acres · High Falls, Ulster County NY',
    address: 'Mohonk Rd, High Falls, NY 12440',
    lat: 41.838,
    lng: -74.121,
    price: 215000,
    acreage: 6.2,
    ppa: 34677,
    scoreOverall: 74,
    tier: 'GOOD MATCH',
    summary:
      'Compact parcel with decent soils (Class III) and no flood exposure, but smaller than your stated minimum. Zoning allows ag accessory structures; lot is on a shared private drive.',
    scores: { soil: 65, flood: 100, price: 82, acreage: 55, zoning: 80, geography: 92, infrastructure: 50, climate: 78 },
    tags: [
      { label: 'Zone X flood', tone: 'green' },
      { label: 'Under acreage min', tone: 'clay' },
    ],
    soil: { class: 3, classLabel: 'Severe limitations', drainage: 'Somewhat poorly', texture: 'Loam / silt loam', primeFarmland: 'No' },
    flood: { zone: 'X', zoneLabel: 'Minimal risk', femaPanel: '36111C0325D', effective: '2014-07-02' },
    parcel: { zoning: 'R-1 — Rural Residential', verifiedAcreage: '6.18', apn: '38.05-1-7' },
    climate: { fire: 2, flood: 1, heat: 3, drought: 2 },
    infra: ['Shared drive', 'Electric on-site'],
    sourcesUsed: ['USDA SDM', 'FEMA NFHL', 'Regrid', 'First Street'],
    sourcesSkipped: [],
  },
  {
    id: 'm4',
    profileId: 'p1',
    unread: false,
    shortlisted: false,
    dismissed: false,
    time: '1d',
    source: 'LandWatch',
    foundAt: 'Apr 17 · 09:03',
    title: '18 acres · Accord, Ulster County NY',
    address: 'Whitfield Rd, Accord, NY 12404',
    lat: 41.782,
    lng: -74.235,
    price: 329000,
    acreage: 18,
    ppa: 18278,
    scoreOverall: 82,
    tier: 'STRONG MATCH',
    summary:
      'Mixed hardwood and pasture, Class II–III soils, stream along the west boundary inside a AE flood corridor. Buildable area is outside the flood zone — flagged for review.',
    scores: { soil: 78, flood: 55, price: 86, acreage: 88, zoning: 85, geography: 90, infrastructure: 70, climate: 80 },
    tags: [
      { label: 'Class II/III', tone: 'gold' },
      { label: 'AE on west edge', tone: 'clay' },
      { label: 'Agricultural', tone: 'gold' },
    ],
    soil: { class: 2, classLabel: 'Good — moderate limitations', drainage: 'Well drained', texture: 'Loam', primeFarmland: 'Partial' },
    flood: { zone: 'AE (partial)', zoneLabel: 'High risk on stream corridor', femaPanel: '36111C0425D', effective: '2014-07-02' },
    parcel: { zoning: 'RA — Rural Agricultural', verifiedAcreage: '17.83', apn: '68.04-1-3' },
    climate: { fire: 2, flood: 3, heat: 3, drought: 2 },
    infra: ['Stream', 'Road frontage', 'Electric on-site'],
    sourcesUsed: ['USDA SDM', 'FEMA NFHL', 'Regrid', 'First Street'],
    sourcesSkipped: [],
  },
  {
    id: 'm5',
    profileId: 'p1',
    unread: false,
    shortlisted: false,
    dismissed: false,
    time: '2d',
    source: 'LandWatch',
    foundAt: 'Apr 16 · 16:22',
    title: '9.1 acres · Marbletown, Ulster County NY',
    address: 'Dug Hill Rd, Marbletown, NY 12401',
    lat: 41.893,
    lng: -74.101,
    price: 275000,
    acreage: 9.1,
    ppa: 30220,
    scoreOverall: 78,
    tier: 'GOOD MATCH',
    summary:
      'Open meadow with Class II soils; zoning allows single-family with ag accessory. No observed flood exposure. Missing parcel zoning — fetched manually from county GIS.',
    scores: { soil: 85, flood: 100, price: 78, acreage: 72, zoning: 75, geography: 88, infrastructure: 55, climate: 80 },
    tags: [{ label: 'Class II soil', tone: 'green' }, { label: 'Zone X', tone: 'green' }],
    soil: { class: 2, classLabel: 'Good — moderate limitations', drainage: 'Well drained', texture: 'Silt loam', primeFarmland: 'Yes' },
    flood: { zone: 'X', zoneLabel: 'Minimal risk', femaPanel: '36111C0360D', effective: '2014-07-02' },
    parcel: { zoning: 'R-1 — Rural Residential', verifiedAcreage: null, apn: '55.01-2-9' },
    climate: { fire: 2, flood: 1, heat: 3, drought: 2 },
    infra: ['Road frontage'],
    sourcesUsed: ['USDA SDM', 'FEMA NFHL', 'First Street'],
    sourcesSkipped: ['Regrid (partial)'],
  },
  {
    id: 'm6',
    profileId: 'p1',
    unread: false,
    shortlisted: false,
    dismissed: true,
    time: '3d',
    source: 'LandWatch',
    foundAt: 'Apr 15 · 11:01',
    title: '4 acres · Kerhonkson, Ulster County NY',
    address: 'Berme Rd, Kerhonkson, NY 12446',
    lat: 41.775,
    lng: -74.300,
    price: 489000,
    acreage: 4,
    ppa: 122250,
    scoreOverall: 48,
    tier: 'WEAK MATCH',
    summary:
      'Below acreage minimum, price-per-acre high, and drainage class poor. Retained for transparency; dismissed after review.',
    scores: { soil: 40, flood: 100, price: 35, acreage: 30, zoning: 70, geography: 85, infrastructure: 40, climate: 72 },
    tags: [{ label: 'Poorly drained', tone: 'clay' }, { label: 'Over budget', tone: 'clay' }],
    soil: { class: 5, classLabel: 'Not suited without improvement', drainage: 'Poorly drained', texture: 'Clay loam', primeFarmland: 'No' },
    flood: { zone: 'X', zoneLabel: 'Minimal risk', femaPanel: '36111C0220D', effective: '2014-07-02' },
    parcel: { zoning: 'R-1 — Rural Residential', verifiedAcreage: '4.02', apn: '71.04-3-15' },
    climate: { fire: 2, flood: 1, heat: 3, drought: 2 },
    infra: ['Road frontage'],
    sourcesUsed: ['USDA SDM', 'FEMA NFHL', 'Regrid', 'First Street'],
    sourcesSkipped: [],
  },
];

const DEFAULT_WEIGHTS = {
  flood: 2.0, soil: 1.5, price: 1.5, acreage: 1.0,
  zoning: 1.0, geography: 1.0, climate: 0.8, infrastructure: 0.5,
};

window.LM_DATA = { PROFILES, MATCHES, DEFAULT_WEIGHTS };
