import { beforeEach, describe, expect, it, vi } from 'vitest';
import bcrypt from 'bcrypt';

import * as userRepo from '../repos/userRepo';
import * as jwt from '../lib/jwt';
import { register, login, refresh } from '../services/authService';

vi.mock('../repos/userRepo');
vi.mock('../lib/jwt');

const mockUserRepo = vi.mocked(userRepo);
const mockJwt = vi.mocked(jwt);

const TOKEN_PAIR = {
  accessToken: 'access-tok',
  refreshToken: 'refresh-tok',
  expiresIn: 900,
};

const STORED_USER = {
  id: 'user-1',
  email: 'test@example.com',
  name: 'Test',
  phone: null,
  authProvider: 'email',
  // Real hash of "password123" (cost 12) generated by bcryptjs 3.x — the
  // library in use before the swap to native bcrypt, i.e. what pre-migration
  // rows in the users table actually contain.
  passwordHash: '$2b$12$PFUmClSlhmzbRgdtwiScGuoDWNsxPUdfVjmP3oRhEyOWGQf0PlcYq',
  subscriptionTier: 'free',
  notificationPrefs: null,
  createdAt: new Date(),
  updatedAt: new Date(),
};

beforeEach(() => {
  vi.resetAllMocks();
  mockJwt.generateTokenPair.mockResolvedValue(TOKEN_PAIR);
});

describe('register', () => {
  it('creates user and returns tokens when email is new', async () => {
    mockUserRepo.findByEmail.mockResolvedValue(undefined);
    mockUserRepo.insert.mockResolvedValue(STORED_USER);

    const result = await register('new@example.com', 'password123', 'New User');

    expect(result).toEqual({ ok: true, data: TOKEN_PAIR });
    // Verify password was hashed (not stored in plain text)
    const insertCall = mockUserRepo.insert.mock.calls[0][0];
    expect(insertCall.email).toBe('new@example.com');
    expect(insertCall.passwordHash).not.toBe('password123');
    expect(insertCall.passwordHash).toMatch(/^\$2[aby]\$/); // bcrypt prefix
  });

  // Bug: if bcrypt or DB throws, service should degrade to INTERNAL_ERROR, not crash the request
  it('returns INTERNAL_ERROR when insert throws', async () => {
    mockUserRepo.findByEmail.mockResolvedValue(undefined);
    mockUserRepo.insert.mockRejectedValue(new Error('DB connection lost'));

    const result = await register('new@example.com', 'password123');

    expect(result).toEqual({ ok: false, error: 'INTERNAL_ERROR' });
  });

  it('rejects duplicate email without attempting insert', async () => {
    mockUserRepo.findByEmail.mockResolvedValue(STORED_USER);

    const result = await register('test@example.com', 'password123');

    expect(result).toEqual({ ok: false, error: 'EMAIL_ALREADY_EXISTS' });
    expect(mockUserRepo.insert).not.toHaveBeenCalled();
  });

  // Bug this catches: two concurrent registrations both pass the pre-check, then
  // the loser trips the unique constraint. Without mapping SQLSTATE 23505 this
  // surfaces as a confusing 500 instead of the same EMAIL_ALREADY_EXISTS the
  // pre-check would have returned.
  it('maps a unique-violation race on insert to EMAIL_ALREADY_EXISTS', async () => {
    mockUserRepo.findByEmail.mockResolvedValue(undefined); // pre-check passes
    mockUserRepo.insert.mockRejectedValue(Object.assign(new Error('duplicate key'), { code: '23505' }));

    const result = await register('race@example.com', 'password123');

    expect(result).toEqual({ ok: false, error: 'EMAIL_ALREADY_EXISTS' });
  });
});

describe('login', () => {
  it('returns tokens when password matches', async () => {
    // Create a real hash we can verify against
    const realHash = await bcrypt.hash('correctpassword', 4); // low cost for speed
    mockUserRepo.findByEmail.mockResolvedValue({ ...STORED_USER, passwordHash: realHash });

    const result = await login('test@example.com', 'correctpassword');

    expect(result).toEqual({ ok: true, data: TOKEN_PAIR });
    expect(mockJwt.generateTokenPair).toHaveBeenCalledWith(STORED_USER.id);
  });

  // Migration guard for the bcryptjs -> native bcrypt swap: stored hashes were
  // generated by bcryptjs, so if the replacement ever stops verifying them
  // (different algorithm, prefix handling, or cost drift), every pre-existing
  // user is silently locked out while new registrations keep working.
  it('verifies a legacy bcryptjs-generated hash so pre-migration users can still log in', async () => {
    mockUserRepo.findByEmail.mockResolvedValue(STORED_USER);

    const result = await login('test@example.com', 'password123');

    expect(result).toEqual({ ok: true, data: TOKEN_PAIR });
  });

  it('rejects wrong password without leaking whether email exists', async () => {
    const realHash = await bcrypt.hash('correctpassword', 4);
    mockUserRepo.findByEmail.mockResolvedValue({ ...STORED_USER, passwordHash: realHash });

    const result = await login('test@example.com', 'wrongpassword');

    // Same error code as nonexistent user — no email enumeration
    expect(result).toEqual({ ok: false, error: 'INVALID_CREDENTIALS' });
    expect(mockJwt.generateTokenPair).not.toHaveBeenCalled();
  });

  it('rejects nonexistent email with same error as wrong password', async () => {
    mockUserRepo.findByEmail.mockResolvedValue(undefined);

    const result = await login('nobody@example.com', 'password123');

    expect(result).toEqual({ ok: false, error: 'INVALID_CREDENTIALS' });
  });

  // Bug this catches: an early `if (!user) return` (the pre-cge.4 behavior) skips
  // bcrypt entirely for unknown emails, so they respond measurably faster than a
  // wrong-password attempt — a timing oracle for account enumeration. Login must
  // spend a bcrypt comparison even when the email doesn't exist.
  it('still performs a bcrypt comparison when the email is unknown (constant-time)', async () => {
    mockUserRepo.findByEmail.mockResolvedValue(undefined);
    const compareSpy = vi.spyOn(bcrypt, 'compare');

    const result = await login('nobody@example.com', 'password123');

    expect(result).toEqual({ ok: false, error: 'INVALID_CREDENTIALS' });
    expect(compareSpy).toHaveBeenCalledTimes(1);
    // never a truthy match against the dummy hash
    await expect(compareSpy.mock.results[0].value).resolves.toBe(false);

    compareSpy.mockRestore();
  });

  // Same side-channel for OAuth accounts that have no password hash: must not
  // short-circuit before the comparison.
  it('still performs a bcrypt comparison for a passwordless (OAuth) user', async () => {
    mockUserRepo.findByEmail.mockResolvedValue({ ...STORED_USER, passwordHash: null });
    const compareSpy = vi.spyOn(bcrypt, 'compare');

    const result = await login('test@example.com', 'password123');

    expect(result).toEqual({ ok: false, error: 'INVALID_CREDENTIALS' });
    expect(compareSpy).toHaveBeenCalledTimes(1);

    compareSpy.mockRestore();
  });

  // Bug: user exists via OAuth (no password) — bcrypt.compare with null crashes
  it('rejects user with no password hash (OAuth user)', async () => {
    mockUserRepo.findByEmail.mockResolvedValue({ ...STORED_USER, passwordHash: null });

    const result = await login('test@example.com', 'password123');

    expect(result).toEqual({ ok: false, error: 'INVALID_CREDENTIALS' });
  });
});

describe('refresh', () => {
  it('returns new token pair when refresh token is valid and user exists', async () => {
    mockJwt.verifyToken.mockResolvedValue({ sub: 'user-1' });
    mockUserRepo.findById.mockResolvedValue(STORED_USER);

    const result = await refresh('valid-refresh-token');

    expect(result).toEqual({ ok: true, data: TOKEN_PAIR });
    expect(mockJwt.verifyToken).toHaveBeenCalledWith('valid-refresh-token', 'refresh');
  });

  it('rejects an invalid/expired refresh token', async () => {
    mockJwt.verifyToken.mockResolvedValue(null);

    const result = await refresh('expired-token');

    expect(result).toEqual({ ok: false, error: 'INVALID_REFRESH_TOKEN' });
    expect(mockUserRepo.findById).not.toHaveBeenCalled();
  });

  // Bug: if DB throws during refresh, should not crash
  it('returns INTERNAL_ERROR when findById throws', async () => {
    mockJwt.verifyToken.mockResolvedValue({ sub: 'user-1' });
    mockUserRepo.findById.mockRejectedValue(new Error('DB timeout'));

    const result = await refresh('valid-token');

    expect(result).toEqual({ ok: false, error: 'INTERNAL_ERROR' });
  });

  // Bug: user deleted between token issuance and refresh — stale token shouldn't work
  it('rejects refresh for a deleted user', async () => {
    mockJwt.verifyToken.mockResolvedValue({ sub: 'deleted-user' });
    mockUserRepo.findById.mockResolvedValue(undefined);

    const result = await refresh('valid-but-orphaned-token');

    expect(result).toEqual({ ok: false, error: 'USER_NOT_FOUND' });
    expect(mockJwt.generateTokenPair).not.toHaveBeenCalled();
  });
});
